- name: check root access and init root password
  shell: >-
    {{ myroot }} -p'{{ mysql_root_pass }}' -e "select 1;" || {{ myroot }} -e '
        SET SQL_LOG_BIN=0;
        ALTER USER `root`@`localhost` IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_pass }}";
        CREATE USER `root`@`127.0.0.1` IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_pass }}";
        CREATE USER `root`@`%` IDENTIFIED WITH mysql_native_password BY "{{ mysql_root_pass }}";
        GRANT ALL PRIVILEGES ON *.* TO `root`@`127.0.0.1` WITH GRANT OPTION;
        GRANT ALL PRIVILEGES ON *.* TO `root`@`%` WITH GRANT OPTION;
        FLUSH PRIVILEGES;
        SET SQL_LOG_BIN=1;'

